name: smart_size_converter
description: "A smart shoe and clothing size converter app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Für einfache Daten-Speicherung (Profile, Einstellungen)
  shared_preferences: ^2.5.3
  # Falls du später doch Dateien oder Bilder speichern willst
  path_provider: ^2.1.5
  # Standard Icons
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Hilft dir, sauberen Code zu schreiben
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/